name: Angular CI
on:
    push:
        branches: [ master ]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Install deps
                run: npm ci
            -   name: Build app
                run: npm run build
            -   name: All things angular
                uses: AhsanAyaz/angular-deploy-gh-pages-actions@v4
                with:
                    github_access_token: ${{ secrets.GITHUB_TOKEN }}
                    deploy_branch: master

permissions:
    contents: write
