name: Angular CI
on:
    push:
        branches: [ master ]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Install deps
                run: npm ci
            -   name: Build app
                run: npm run build
            -   name: Deploy to GitHub Pages
                uses: actions/deploy-pages@v4
