name: Angular CI
on:
    push:
        branches: [ master ]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Install deps
                run: npm ci
            -   name: Build app
                run: npm run build:prod
            -   name: All things angular
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    folder: dist/giphy-showcase

permissions:
    contents: write
